# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(978, 755)
        Widget.setMouseTracking(True)
        Widget.setStyleSheet("\n"
"        background-color: #ccc;    /* White background for table cells */\n"
"        color: #000;               /* Black text in cells */\n"
"        font-family: \"Segoe UI\";\n"
"        font-size: 10pt;\n"
"    ")
        self.pushButton = QtWidgets.QPushButton(parent=Widget)
        self.pushButton.setGeometry(QtCore.QRect(670, 30, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"    color: #000;              /* black text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 10pt;")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(parent=Widget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 80, 901, 651))
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setStyleSheet(" background-color: #fff;    /* White background for table cells */")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.lineEdit = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit.setGeometry(QtCore.QRect(480, 30, 181, 25))
        self.lineEdit.setStyleSheet("background-color: #fff;   /* white background */\n"
"    color: #000;              /* black text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12pt;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_SelectFile = QtWidgets.QPushButton(parent=Widget)
        self.pushButton_SelectFile.setGeometry(QtCore.QRect(240, 30, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButton_SelectFile.setFont(font)
        self.pushButton_SelectFile.setObjectName("pushButton_SelectFile")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 30, 181, 25))
        self.lineEdit_2.setStyleSheet("background-color: #fff;   /* white background */\n"
"    color: #000;              /* black text */\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 12pt;")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton.setText(_translate("Widget", " Search Item"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "Sheet"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "Summary"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "Price"))
        self.pushButton_SelectFile.setText(_translate("Widget", "Select File"))
